insert into produtos (nome, marca, slug, descricao) values ('Arroz branco', 'pequeno grao', 'arroz-branco', '5 quilos');
insert into produtos (nome, marca, slug, descricao) values ('Feijão', 'Feijão do Jão', 'feijao-preto', '1 quilo');
insert into produtos (nome, marca, slug, descricao) values ('Azeite', 'Gota Da Lívia', 'azeite', 'Azeite Puro');
insert into produtos (nome, marca, slug, descricao) values ('Óleo', 'Puro Óleo', 'oleo-amarelo', 'Ideal para fritar seus pastéis, batatas ou anéis de cebola');
insert into produtos (nome, marca, slug, descricao) values ('Açúcar', 'Bem Formigueiro', 'acucar-refinado', 'O açúcar mais doce que você já viu, mas cuidado com a diabete');
insert into produtos (nome, marca, slug, descricao) values ('Café', 'Cafézin', 'cafe-forte', 'O sabor da fazenda direto para sua casa');
insert into produtos (nome, marca, slug, descricao) values ('Arroz integral', 'pequeno grâo', 'arroz-integral', '1 quilo');
insert into produtos (nome, marca, slug, descricao) values ('Achocolatado', 'Nescau','chocolate-po', 'Energia que dá força');
insert into produtos (nome, marca, slug, descricao) values ('Molho de Tomate', 'Heinz', 'extrato-tomate', 'Compedaços de tomate');
insert into produtos (nome, marca, slug, descricao) values ('Cereal', 'Nestle', 'cereal', 'Cereal matinal tradicional');
insert into produtos (nome, marca, slug, descricao) values ('Milho Verde', 'Quero', 'milho-enlatado', 'Milho Verde pronto para servir');
insert into produtos (nome, marca, slug, descricao) values ('Ervilha', 'Quero', 'ervilha-enlatada', 'Ervilha pronta para servir');
insert into produtos (nome, marca, slug, descricao) values ('Biscoito', 'É bolacha!', 'biscoito-morango', 'Biscoito de chocolate com recheio de morango');
insert into produtos (nome, marca, slug, descricao) values ('Biscoito', 'Nesfit', 'biscoito-salgado', 'Biscoito integral com gergelim');
insert into produtos (nome, marca, slug, descricao) values ('Pão Francês', 'Da Casa', 'pao-frances', 'Pão fresquinho para manhã ou tarde');
insert into produtos (nome, marca, slug, descricao) values ('Rosquinha', 'Da Casa', 'rosquinha-acucar', 'Rosquinha Docinha');
insert into produtos (nome, marca, slug, descricao) values ('Pão de queijo', 'Vó da fazenda', 'pao-queijo', 'três tipos de queijo no seu pão');
insert into produtos (nome, marca, slug, descricao) values ('Maça', 'fuji', 'maça-vermelha', 'Valor cobrado em Kg');
insert into produtos (nome, marca, slug, descricao) values ('Couve', 'Da roça', 'couve-manteiga', '2.50 o maço');
insert into produtos (nome, marca, slug, descricao) values ('Abacate', 'Da roça', 'abacate-avocado', '2 por 5, 4 por 10');
insert into produtos (nome, marca, slug, descricao) values ('Costela', 'Friboi','costela-bovina', 'Peça perfeita para seu churras!');
insert into produtos (nome, marca, slug, descricao) values ('Linguiça', 'Aurora', 'linguica-calabresa', 'Disponivel para pesar ou na bandeja');
insert into produtos (nome, marca, slug, descricao) values ('Shampoo', 'Palmolive', 'shampoo', 'Para todos os tipos de cabelo');
insert into produtos (nome, marca, slug, descricao) values ('Sabonete', 'Francis', 'sabonete-barra', 'Cheiro de flores');
insert into produtos (nome, marca, slug, descricao) values ('Água com gás', 'São Lourenço', 'agua-gas', 'Água gaserificada naturalmente');
insert into produtos (nome, marca, slug, descricao) values ('Fanta Laranja', 'Coca Cola', 'fanta-cola', 'Se a Fanta quebrar, a Coca Cola');